CREATE TABLE rick_and_morty_v6
(
	id INTEGER NOT NULL ENCODE az64,
	name VARCHAR(100) ENCODE lzo,
	status VARCHAR(50) ENCODE lzo,
	species VARCHAR(50) ENCODE lzo,
	"type" VARCHAR(50) ENCODE lzo,
	gender VARCHAR(20) ENCODE lzo,
	created TIMESTAMP WITHOUT TIME ZONE ENCODE az64,
	"timestamp" TIMESTAMP WITHOUT TIME ZONE ENCODE az64,
	PRIMARY KEY (id)
);
